---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_program_summary_overview.html 
keywords: fexpod, express, cisco, ucs, series, c, aff, c190, nva, deployment 
summary: 支援基礎組態的支援中心及支援中心、可靈活調整規模及最佳化、以因應多種不同的使用案例和需求。FlexPod FlexPod 
---
= NVA-1142-部署：FlexPod 採用Cisco UCS C系列與NetApp AFF 支援中心190系列- NVA部署的不二之選
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp的Savita Kumari

產業趨勢顯示、共享基礎架構和雲端運算正在進行龐大的資料中心轉型。此外、企業組織也需要一套簡單有效的解決方案、讓遠端辦公室和分公司使用他們在資料中心熟悉的技術。

NetApp®Express是預先設計的最佳實務資料中心架構、建置於Cisco Unified Computing System（Cisco UCS）、Cisco Nexus系列交換器及NetApp®儲存技術之上。FlexPod與之類似的是、在整個IT基礎架構環境中、透過更小規模的方式、實現管理協同效益。FlexPod FlexPod支援虛擬化、裸機作業系統和企業工作負載的最佳平台、就是資料中心和不支援的平台。FlexPod FlexPod

支援基礎組態的支援中心及支援中心、可靈活調整規模及最佳化、以因應多種不同的使用案例和需求。FlexPod FlexPod現有FlexPod 的VMware資料中心客戶可以FlexPod 使用他們習慣使用的工具來管理自己的VMware Express系統。全新FlexPod 的Express客戶可隨著FlexPod 環境的成長、輕鬆轉換至管理功能「不支援不支援的資料中心」。

適用於遠端辦公室和分公司、以及中小型企業的最佳基礎架構基礎。FlexPod對於想要為專屬工作負載提供基礎架構的客戶而言、這也是最佳解決方案。

支援簡單易管理的基礎架構、幾乎適用於任何工作負載。FlexPod
