---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: 本文件詳細說明如何設定完全備援且高度可用FlexPod 的Express系統。為了反映這種備援、每個步驟中所設定的元件都稱為元件A或元件B 
---
= 總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本文件詳細說明如何設定完全備援且高度可用FlexPod 的Express系統。為了反映這種備援、每個步驟中所設定的元件都稱為元件A或元件B例如、控制器A和控制器B會識別本文件中所配置的兩個NetApp儲存控制器。交換器A和交換器B會識別一對Cisco Nexus交換器。

此外、本文也說明配置多個Cisco UCS主機的步驟、這些主機會依序識別為伺服器A、伺服器B等。

為了指出您應該在步驟中加入與環境相關的資訊、「」<<text >會顯示為命令結構的一部分。請參閱以下「VLAN create」命令範例：

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
本文件可讓您完整設定FlexPod 《支援不支援不支援的使用者介面》環境。在此程序中、您需要執行各種步驟、才能插入客戶專屬的命名慣例、IP位址和虛擬區域網路（VLAN）配置。下表說明部署所需的VLAN、如本指南所述。此表格可根據特定站台變數完成、並用於實作文件組態步驟。


NOTE: 如果您使用不同的頻內和頻外管理VLAN、則必須在它們之間建立第3層路由。此驗證使用通用管理VLAN。

|===
| VLAN名稱 | VLAN用途 | VLAN ID |  


| 管理VLAN | 管理介面的VLAN | 3437 | vSwitch0 


| NFS VLAN | NFS流量的VLAN | 3438 | vSwitch0 


| VMware VMotion VLAN | 指定用於將虛擬機器（VM）從一部實體主機移至另一部主機的VLAN | 3441. | vSwitch0 


| VM流量VLAN | VM應用程式流量的VLAN | 3442. | vSwitch0 


| iSCSI-A-VLAN | 光纖A上iSCSI流量的VLAN | 3439 | iScsiBootvSwitch 


| iSCSI-B VLAN | 光纖B上iSCSI流量的VLAN | 3440 | iScsiBootvSwitch 


| 原生VLAN | 指派無標記框架的VLAN | 2. |  
|===
在整個設定過程中、需要使用VLAN編號FlexPod 。這些VLAN稱為「<<var_xxxx_vlan->>」、其中「XXXX」是VLAN的用途（例如iSCSI-A）。

在此驗證中建立了兩個VSwitches。

下表列出解決方案VSwitches。

|===
| vSwitch名稱 | 作用中的介面卡 | 連接埠 | MTU | 負載平衡 


| vSwitch0 | vmnic2、vmnic4 | 預設（120） | 9000 | 根據IP雜湊進行路由 


| iScsiBootvSwitch | vmnic3、vmnic5 | 預設（120） | 9000 | 根據來源虛擬連接埠ID進行路由。 
|===

NOTE: 負載平衡的IP雜湊方法需要使用靜態（模式開啟）連接埠通道的SRC-DST-IP位址通道、為基礎實體交換器進行適當的組態設定。萬一交換器組態可能造成連線中斷、請暫時關閉Cisco交換器上兩個相關的上行鏈路連接埠之一、以便在疑難排解連接埠通道設定時、恢復與ESXi管理vmkernel連接埠的通訊。

下表列出所建立的VMware VM。

|===
| VM說明 | 主機名稱 


| VMware vCenter Server | FlexPod與VCSA 


| 虛擬儲存主控台 | FlexPod VSC 
|===