---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: 「資料中心」組態具有最低的硬體需求、包括但不限於交換器、網路互連、伺服器和NetApp儲存控制器。FlexPod 
---
= 最低硬體需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
「資料中心」組態具有最低的硬體需求、包括但不限於交換器、網路互連、伺服器和NetApp儲存控制器。FlexPod

下列最低硬體需求為基礎：FlexPod

* 兩台 Cisco Nexus 交換器採用備援組態。此組態可由兩台前面提到的 Cisco Nexus 9000 系列備援交換器組成。這兩台交換器應為同一型號，並設定為相同的操作模式。



NOTE: 如果您要部署 ACI 架構，則必須遵守下列附加要求：* 將 Cisco Nexus 9000 系列交換器部署在葉脊拓撲中。* 使用三個 Cisco Application Policy Infrastructure Controllers （APIC）。

* 如果使用 UCS C 系列機架伺服器或 X 系列模組化系統，則需要兩台 Cisco UCS 6400、6500 或 6600 系列 Fabric Interconnect，並採用備援組態。
* 兩台 Cisco UCS C 系列機架伺服器，具備 FI 連線和 Intersight 管理組態 （IMM）；或 Cisco UCS X-Series Direct，具備 Cisco IMM；或 Cisco UCS X-Series Modular，具備 Cisco Intersight 管理組態 （IMM）。



NOTE: 如果您使用的是沒有 FI 連線的 UCS 機架伺服器，則可以使用 CIMC 或 Intersight 獨立式模式進行管理。

* 兩台 NetApp AFF、NetApp ASA 或 NetApp FAS 控制器以高可用度 （HA） 配對組態部署為雙節點叢集。如果使用 NetApp AFX，則至少需要四台 NetApp AFX 控制器，並部署為四節點 HA 叢集，同時還需要一對叢集互連交換器。
* 對於沒有內建磁碟架的儲存控制器，至少需要一個 NetApp 磁碟架。

