---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp 儲存控制器在 FlexPod Express 架構中提供開機與應用程式資料儲存的儲存基礎。本節列出 FlexPod Express 架構中不同的 NetApp 儲存選項。 
---
= NetApp元件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp儲存控制器為FlexPod 支援開機和應用程式資料儲存的功能、提供了在《不可靠的資料保護技術（NetApp Express）」架構中的儲存基礎。本節列出FlexPod 了NetApp在《不只是用作解決方案的基礎架構」中的不同選項。



== NetApp儲存控制器選項

FlexPod Express 架構需要冗餘的 AFF、ASA 或 FAS 系列控制器。這些控制器運行 ONTAP 軟體。訂購儲存控制器時，可選擇預先安裝所需的軟體版本。對於 ONTAP，叢集可以採用一對叢集互連交換器進行部署，也可以採用無交換器叢集配置。


NOTE: 無交換器叢集組態僅支援雙節點組態。超過 4 個節點的組態需要叢集互連交換器，雙節點組態則為選用。

根據所選儲存平台的不同，可提供不同的選項和組態。有關這些附加元件的詳細資訊，請諮詢您的銷售代表。

下表所列的控制器系列適用於 FlexPod 解決方案，因為它們與 Cisco Nexus 交換器的連接無縫銜接。有關各控制器型號的具體相容性詳情，請參閱 http://hwu.netapp.com/["NetApp Hardware Universe"^]。

|===
| NetApp 入門級儲存系列，適用於 FlexPod Express | 模型 | 技術規格 


.2+| A系列AFF | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["A系列文件AFF"] 


| A30 


| AFF C 系列 | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C 系列文件"] 


.2+| ASA A 系列 | A20 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA A 系列文件"] 


| A30 


| ASA C 系列 | C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA C 系列文件"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 說明文件"] 


| FAS 2820 
|===


== NetApp磁碟櫃與磁碟

儲存控制器至少需要一個 NetApp 磁碟櫃。

所選的NetApp機櫃類型決定該機櫃中可用的磁碟機類型。


NOTE: 如需所有磁碟櫃和磁碟零件編號、請洽詢您的銷售代表。

如需受支援磁碟機的詳細資訊、請按Hardware Universe 一下下表中的NetApp功能鏈結、然後選取「Supported Drives（支援的磁碟機）」。

下表列出NetApp磁碟櫃選項、以及每種磁碟櫃類型所支援的磁碟機、這些磁碟機可在NetApp Hardware Universe 支援上找到。點選Hardware Universe 「更新」連結、選擇ONTAP 您所使用的版本、然後選擇機櫃類型。在機櫃映像下、按一下「Supported Drives（支援的磁碟機）」以查看特定版本ONTAP 的支援的磁碟機、以及磁碟櫃。

|===
| 磁碟櫃 | 技術規格 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe 支援磁碟櫃與儲存媒體的磁碟機"] 


| DS224C 


| DS460C 


| NS224 


| NS224 搭配 NSM100B 
|===


== NetApp軟體授權選項

下表列出 NetApp 軟體授權選項。

|===
| NetApp軟體授權 | 技術規格 


| ONTAP One 或 ONTAP base 適用於 AFF 和 FAS .2+| 如需更多授權資訊、請洽詢您的NetApp銷售團隊。 


| 適用於 ASA 的 ONTAP One for SAN 
|===


== NetApp支援授權選項

需要使用支援、而這些授權的零件編號會根據所選的選項而有所不同。SupportEdge Premium FlexPod

下表列出 NetApp AFF、ASA 和 FAS 儲存系統的 NetApp 支援授權選項。

|===
| NetApp支援授權 | 產品編號 | 技術規格 


| 現場4小時；月數：SupportEdge 36 | CS -O2 - 4小時 | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===