---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp 儲存控制器在 FlexPod Express 架構中提供開機與應用程式資料儲存的儲存基礎。本節列出 FlexPod Express 架構中不同的 NetApp 儲存選項。 
---
= NetApp元件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
NetApp儲存控制器為FlexPod 支援開機和應用程式資料儲存的功能、提供了在《不可靠的資料保護技術（NetApp Express）」架構中的儲存基礎。本節列出FlexPod 了NetApp在《不只是用作解決方案的基礎架構」中的不同選項。



[[netapp-storage-controller-options]]
== NetApp儲存控制器選項

FlexPod Express 架構需要冗餘的 AFF、ASA 或 FAS 系列控制器。這些控制器執行 ONTAP 軟體。訂購儲存控制器時，可以預先在控制器上載入偏好的軟體版本。對於 ONTAP，可以使用一對叢集互連交換器或在無交換器叢集組態中部署叢集。


NOTE: 無交換器式叢集組態僅適用於雙節點組態。具有 4 個或更多節點的組態需要叢集互連交換器，雙節點組態則可選用。

根據所選儲存平台，可提供不同的選項和配置。有關這些附加元件的詳細資訊，請諮詢您的銷售代表。

下表所列的控制器系列適用於 FlexPod 解決方案，因為它們與 Cisco Nexus 交換器的連接無縫銜接。有關各控制器型號的具體相容性詳情，請參閱 http://hwu.netapp.com/["NetApp Hardware Universe"^]。

|===
| NetApp 入門級儲存系列，適用於 FlexPod Express | 模型 | 技術規格 


.2+| A系列AFF | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["A系列文件AFF"] 


| A30 


| AFF C 系列 | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["AFF C 系列文件"] 


.2+| ASA A 系列 | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["ASA 說明文件"] 


| A30 


| ASA C 系列 | C30 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS 說明文件"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== NetApp磁碟櫃與磁碟

對於沒有內建磁碟架的儲存控制器，至少需要一個 NetApp 磁碟架。所選的 NetApp 磁碟架類型決定了該磁碟架內可用的磁碟機類型。


NOTE: 如需所有磁碟櫃和磁碟零件編號、請洽詢您的銷售代表。

下表列出了 NetApp 磁碟架選項（適用於 FlexPod Express），以及其技術規格的連結。

若要取得磁碟櫃支援的磁碟機列表，請前往 link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe"^]，在 *Products > Storage > Shelves* 下選擇 *ONTAP (AFF, ASA, FAS)*，然後選擇您正在使用的 ONTAP 版本，再選擇磁碟櫃類型（例如：*DS212C*），然後按一下 *Show Results*。按一下 *Supported Drives* 即可查看特定 ONTAP 版本和磁碟櫃支援的磁碟機。

|===
| 磁碟櫃 | 技術規格 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["磁碟架和儲存媒體"] 


| DS224C 


| DS460C 


| NS224 


| NS224 搭配 NSM100B 
|===


[[netapp-software-licensing-options]]
== NetApp軟體授權選項

下表列出 NetApp 軟體授權選項。

|===
| NetApp軟體授權 | 技術規格 


| ONTAP One 適用於 AFF 和 FAS .2+| 如需更多授權資訊、請洽詢您的NetApp銷售團隊。 


| 適用於 ASA 的 ONTAP One for SAN 
|===
有關 NetApp 軟體授權的詳細資訊，請參閱此連結： https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["NetApp軟體授權"^]。



[[netapp-support-licensing-options]]
== NetApp支援授權選項

需要使用支援、而這些授權的零件編號會根據所選的選項而有所不同。SupportEdge Premium FlexPod

下表列出 NetApp AFF、ASA 和 FAS 儲存系統的 NetApp 支援授權選項。

|===
| NetApp支援授權 | 技術規格 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===