---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-san-configuration.html 
keywords: san, configuration, host utility kit, discover storage, multipathing, physical volume, group, logical volume, file system, snapmirror 
summary: 本節說明EHR所需的主機端組態、以使軟體能與NetApp儲存設備最佳整合。在此區段中、我們特別討論Linux作業系統的主機整合。 
---
= SAN組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-installation-and-configuration.html["先前：安裝與組態。"]

[role="lead"]
本節說明EHR所需的主機端組態、以使軟體能與NetApp儲存設備最佳整合。在此區段中、我們特別討論Linux作業系統的主機整合。使用 https://imt.netapp.com/matrix/["NetApp互通性對照表工具IMT （不含）"^] 驗證所有軟體與韌體版本。


NOTE: 下列組態步驟是本解決方案中使用的CentOS 8主機專屬的設定步驟。



== NetApp主機公用程式套件

NetApp建議您在連線至及存取NetApp儲存系統的主機作業系統上安裝NetApp主機公用程式套件（主機公用程式）。支援原生Microsoft多重路徑I/O（MPIO）。作業系統必須支援非對稱邏輯單元存取（ALUA）、才能執行多重路徑作業。安裝主機公用程式會設定NetApp儲存設備的主機匯流排介面卡（HBA）設定。

NetApp主機公用程式可下載 https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab["請按這裡"^]。在此解決方案中、我們已在主機上安裝Linux Host Utilities 7.1。

....
[root@hc-cloud-secure-1 ~]# rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64.rpm
....


== 探索ONTAP 功能

請確定iSCSI服務在應登入時執行。若要為目標上的特定入口網站或目標上的所有入口網站設定登入模式、請使用 `iscsiadm` 命令。

....
[root@hc-cloud-secure-1 ~]# rescan-scsi-bus.sh
[root@hc-cloud-secure-1 ~]# iscsiadm -m discovery -t sendtargets -p <iscsi-lif-ip>
[root@hc-cloud-secure-1 ~]# iscsiadm -m node -L all
....
現在您可以使用了 `sanlun` 可顯示有關連接主機的LUN的信息。請確定您以root身分登入主機。

....
[root@hc-cloud-secure-1 ~]# sanlun lun show
controller(7mode/E-Series)/
                                    device    host             lun
vserver(cDOT/FlashRay) lun-pathname filename  adapter protocol size   product
-----------------------------------------------------------------------------
Healthcare_SVM                       /dev/sdb host33  iSCSI    200g    cDOT
                       /vol/hc_iscsi_vol/iscsi_lun1

Healthcare_SVM                       /dev/sdc host34  iSCSI    200g    cDOT
                       /vol/hc_iscsi_vol/iscsi_lun1
....


== 設定多重路徑

Device Mapper多路徑（DM-多 路徑）是Linux中的原生多重路徑公用程式。它可用於備援和改善效能。它會彙總或合併伺服器與儲存設備之間的多重I/O路徑、因此在作業系統層級建立單一裝置。

. 在系統上設定DM-MultiPath之前、請先確認系統已更新且已包含 `device-mapper-multipath` 套件：
+
....
[root@hc-cloud-secure-1 ~]# rpm -qa|grep multipath
device-mapper-multipath-libs-0.8.4-31.el8.x86_64
device-mapper-multipath-0.8.4-31.el8.x86_64
....
. 組態檔是 `/etc/multipath.conf` 檔案：如下所示更新組態檔。
+
....
[root@hc-cloud-secure-1 ~]# cat /etc/multipath.conf
defaults {
   path_checker      readsector0
   no_path_retry      fail
}
devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
....
. 啟用並啟動多重路徑服務。
+
....
[root@hc-cloud-secure-1 ~]# systemctl enable multipathd.service
[root@hc-cloud-secure-1 ~]# systemctl start  multipathd.service
....
. 新增可載入的核心模組 `dm-multipath` 並重新啟動多重路徑服務。最後、請檢查多重路徑狀態。
+
....
[root@hc-cloud-secure-1 ~]# modprobe -v dm-multipath
insmod /lib/modules/4.18.0-408.el8.x86_64/kernel/drivers/md/dm-multipath.ko.xz

[root@hc-cloud-secure-1 ~]# systemctl restart multipathd.service

[root@hc-cloud-secure-1 ~]# multipath -ll
3600a09803831494c372b545a4d786278 dm-2 NETAPP,LUN C-Mode
size=200G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| `- 33:0:0:0 sdb 8:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
`- 34:0:0:0 sdc 8:32 active ready running
....



NOTE: 如需這些步驟的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap-sanhost/hu_centos_80.html["請按這裡"^]。



== 建立實體磁碟區

使用 `pvcreate` 初始化區塊裝置以做為實體磁碟區的命令。初始化類似於格式化檔案系統。

....
[root@hc-cloud-secure-1 ~]# pvcreate /dev/sdb
Physical volume "/dev/sdb" successfully created.
....


== 建立Volume群組

若要從一或多個實體磁碟區建立磁碟區群組、請使用 `vgcreate` 命令。此命令會依名稱建立新的磁碟區群組、並至少新增一個實體磁碟區。

....
[root@hc-cloud-secure-1 ~]# vgcreate datavg /dev/sdb
Volume group "datavg" successfully created.
....
。 `vgdisplay` 命令可用於以固定形式顯示Volume群組內容（例如大小、範圍、實體磁碟區數量等）。

....
[root@hc-cloud-secure-1 ~]# vgdisplay datavg
  --- Volume group ---
  VG Name               datavg
  System ID
  Format                lvm2
  Metadata Areas        1
  Metadata Sequence No  1
  VG Access             read/write
  VG Status             resizable
  MAX LV                0
  Cur LV                0
  Open LV               0
  Max PV                0
  Cur PV                1
  Act PV                1
  VG Size               <200.00 GiB
  PE Size               4.00 MiB
  Total PE              51199
  Alloc PE / Size       0 / 0
  Free  PE / Size       51199 / <200.00 GiB
  VG UUID               C7jmI0-J0SS-Cq91-t6b4-A9xw-nTfi-RXcy28
....


== 建立邏輯Volume

當您建立邏輯Volume時、邏輯Volume會使用組成Volume群組的實體磁碟區上的可用範圍、從Volume群組中進行切分。

....
[root@hc-cloud-secure-1 ~]# lvcreate - l 100%FREE -n datalv datavg
Logical volume "datalv" created.
....
此命令會建立一個稱為的邏輯Volume `datalv` 這會使用Volume群組中所有未配置的空間 `datavg`。



== 建立檔案系統

....
[root@hc-cloud-secure-1 ~]# mkfs.xfs -K /dev/datavg/datalv
meta-data=/dev/datavg/datalv     isize=512    agcount=4, agsize=13106944 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=52427776, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=25599, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
....


== 建立要掛載的資料夾

....
[root@hc-cloud-secure-1 ~]# mkdir /file1
....


== 掛載檔案系統

....
[root@hc-cloud-secure-1 ~]# mount -t xfs /dev/datavg/datalv /file1

[root@hc-cloud-secure-1 ~]# df -k
Filesystem                1K-blocks    Used Available Use% Mounted on
devtmpfs                    8072804       0   8072804   0% /dev
tmpfs                       8103272       0   8103272   0% /dev/shm
tmpfs                       8103272    9404   8093868   1% /run
tmpfs                       8103272       0   8103272   0% /sys/fs/cgroup
/dev/mapper/cs-root        45496624 5642104  39854520  13% /
/dev/sda2                   1038336  258712    779624  25% /boot
/dev/sda1                    613184    7416    605768   2% /boot/efi
tmpfs                       1620652      12   1620640   1% /run/user/42
tmpfs                       1620652       0   1620652   0% /run/user/0
/dev/mapper/datavg-datalv 209608708 1494520 208114188   1% /file1
....
如需這些工作的詳細資訊、請參閱頁面 link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/logical_volume_manager_administration/lvm_cli["使用CLI命令進行LVM管理"]。



== 資料產生

 `Dgen.pl`是一個用於 EHR I/O 模擬器 (GenerateIO) 的 perl 腳本資料產生器。 LUN 內的資料由 EHR 產生。 `Dgen.pl`腳本。該腳本旨在創建與 EHR 資料庫中的數據類似的數據。

....
[root@hc-cloud-secure-1 ~]# cd GenerateIO-1.17.3/

[root@hc-cloud-secure-1 GenerateIO-1.17.3]# ./dgen.pl --directory /file1 --jobs 80

[root@hc-cloud-secure-1 ~]# cd /file1/
[root@hc-cloud-secure-1 file1]# ls
dir01  dir05  dir09  dir13  dir17  dir21  dir25  dir29  dir33  dir37  dir41  dir45  dir49  dir53  dir57  dir61  dir65  dir69  dir73  dir77  dir02  dir06  dir10  dir14  dir18  dir22  dir26  dir30  dir34  dir38  dir42  dir46  dir50  dir54  dir58  dir62  dir66  dir70  dir74  dir78  dir03  dir07  dir11  dir15  dir19  dir23  dir27  dir31  dir35  dir39  dir43  dir47  dir51  dir55  dir59  dir63  dir67  dir71  dir75  dir79  dir04  dir08  dir12  dir16  dir20  dir24  dir28  dir32  dir36  dir40  dir44  dir48  dir52  dir56  dir60  dir64  dir68  dir72  dir76  dir80

[root@hc-cloud-secure-1 file1]# df -k .
Filesystem                 1K-blocks  Used       Available  Use%  Mounted on
/dev/mapper/datavg-datalv  209608708  178167156  31441552   85%   /file1
....
執行時 `Dgen.pl` 指令碼預設會使用85%的檔案系統來產生資料。



== 設定內部部署ONTAP 的SnapMirror與Cloud Volumes ONTAP 功能不全的SnapMirror複寫

NetApp SnapMirror可透過LAN或WAN高速複寫資料、因此您可以在虛擬與傳統環境中同時獲得高資料可用度與快速資料複寫。當您將資料複寫到NetApp儲存系統並持續更新次要資料時、資料會保持最新狀態、並在需要時隨時保持可用。不需要外部複寫伺服器。

完成下列步驟、在內部部署ONTAP 的整套系統和CVO之間設定SnapMirror複寫。

. 從導覽選單中，選擇“儲存”>“系統”。
. 在「系統」中，選擇包含來源磁碟區的系統，將其拖曳到要將磁碟區複製到的系統，然後選擇「複製」。
+
其餘步驟說明如何在Cloud Volumes ONTAP 不同時執行的ONTAP 功能叢集之間建立同步關係。

. *來源與目的地對等關係設定。*如果出現此頁面、請選取叢集對等關係的所有叢集間生命體。
. *來源Volume選擇。*選取您要複寫的磁碟區。
. *目的地磁碟類型與分層。*如果目標Cloud Volumes ONTAP 是一個支援系統、請選取目的地磁碟類型、然後選擇是否要啟用資料分層。
. *目的地Volume名稱：*指定目的地Volume名稱、然後選擇目的地Aggregate。如果目的地是ONTAP 一個不必要的叢集、您也必須指定目的地儲存VM。
. *最大傳輸率。*指定資料傳輸的最大傳輸率（以百萬位元組/秒為單位）。
. *複寫原則。*選擇預設原則或按一下*其他原則*、然後選取其中一個進階原則。如需協助、 https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication-policies.html["深入瞭解複寫原則"^]。
. *排程。*選擇一次性複本或週期性排程。有多個預設排程可供使用。如果您想要不同的排程、則必須在上建立新的排程 `destination cluster` 使用System Manager。
. *檢閱*檢閱*檢閱您的選擇、然後按一下*執行*。


如需這些組態步驟的詳細資訊、請參閱 https://docs.netapp.com/us-en/cloud-manager-replication/task-replicating-data.html["請按這裡"^]。

控制台啟動資料複製過程。在此階段，您可以看到在本機ONTAP系統和Cloud Volumes ONTAP之間建立的 *複製* 服務。

在這個叢集中、您可以看到新建立的Volume Cloud Volumes ONTAP 。

您也可以確認內部部署Volume與雲端Volume之間已建立SnapMirror關係。

如需複寫工作的詳細資訊、請參閱* Replication *（複寫*）索引標籤。

link:fhc-cvoe-solution-validation.html["下一步：解決方案驗證。"]
