---
sidebar: sidebar 
permalink: hybrid-cloud/gcp-ncvo-solution-components.html 
keywords: flexpod, cisco intersight, licensing, Terraform Cloud Integration, ICO, NetApp Cloud Volumes ONTAP, Cloud Central, Connector, Active IQ Unified Manager, Hardware, software 
summary: 本節說明實作此解決方案所需的所有解決方案元件。 
---
= 解決方案元件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:gcp-ncvo-solution-overview.html["上一篇：解決方案總覽。"]



== FlexPod

支援針對虛擬化與非虛擬化解決方案、提供一套明確定義的硬體與軟體、為兩者提供整合式基礎。FlexPod包含NetApp的不整儲存設備、Cisco Nexus網路、Cisco MDS儲存網路、以及Cisco Unified Computing System（Cisco UCS）FlexPod ONTAP 。此設計相當靈活、可將網路、運算和儲存設備放入單一資料中心機架、或是根據客戶的資料中心設計進行部署。連接埠密度可讓網路元件容納多種組態。



== Cisco Intersight

Cisco Intersight是SaaS平台、可針對傳統和雲端原生的應用程式和基礎架構、提供智慧型自動化、監控及最佳化功能。此平台可協助IT團隊推動變革、並提供專為混合雲設計的營運模式。Cisco Intersight提供下列優點：

* *更快的交付速度。*由於採用敏捷的軟體開發模式、因此可從雲端或客戶資料中心以服務形式提供、並提供頻繁更新和持續創新的服務。如此一來、客戶就能專注於加速交付業務線。
* *簡化營運。*使用單一安全的SaaS交付工具、搭配通用的庫存、驗證和API、在整個堆疊和所有位置上運作、以簡化營運、消除跨團隊的封閉環境。從內部部署的實體伺服器與Hypervisor管理、到VM、K8s、無伺服器、自動化、 在內部部署和公有雲之間進行最佳化和成本控制。
* *持續最佳化。*使用Cisco Intersight提供的智慧功能、跨越每個層面、以及Cisco技術支援中心、持續最佳化您的環境。這項智慧功能已轉換成建議且可自動執行的動作、讓您能夠即時因應每項變更：從移動工作負載、監控實體伺服器的健全狀況、到您使用的公有雲所建議的成本降低建議。


Cisco Intersight有兩種管理作業模式：UCSM託管模式（UMM）和Intersight託管模式（IMMM）。您可以在初始設定光纖互連時、為光纖附加的Cisco UCS系統選取原生Umm或IMMM。在此解決方案中、使用原生的IMM.



=== Cisco Intersight授權

Cisco Intersight使用多層的訂閱型授權。

Cisco Intersight授權層如下：

* * Cisco Intersight Essentials *包含所有基礎功能及下列功能：
+
** Cisco UCS Central
** Cisco IMC主管權利
** 使用伺服器設定檔進行原則型組態
** 韌體管理
** 評估與硬體相容性清單（HCL）的相容性


* * Cisco Intersight Advantage *包含Essentials層級的功能與特色、以及下列功能：
+
** 跨實體運算、網路、儲存設備、VMware虛擬化及AWS公有雲的小工具、庫存、容量、使用率功能及跨網域庫存關聯。
** Cisco安全性摘要報告服務、客戶可在此收到重要的安全性警示和受影響端點裝置的現場通知。


* * Cisco Intersight Premier *除了優勢層提供的功能之外、Cisco Intersight Premier還提供下列功能：
+
** Intersight Cloud Orchestrator（ICO）適用於Cisco與協力廠商運算、網路、儲存設備、整合式系統、虛擬化、 容器和公有雲平台
** Cisco UCS Director的完整訂購權利、不需額外付費。




如需每個授權所支援之Intersight授權和功能的詳細資訊、請參閱 https://intersight.com/help/saas/getting_started/licensing_requirements["請按這裡"^]。


NOTE: 在此解決方案中、我們使用Intersight Cloud Orchestrator和Intersight Service for HashiCorp Terraform。這些功能適用於具有Intersight Premier授權的使用者、因此必須啟用此授權層級。



=== Terraform Cloud與ICO整合

您可以使用Cisco Intersight Cloud Orchestrator（ICO）建立及執行稱為Terraform Cloud（TFC）API的工作流程。「叫用Web API要求」工作可支援以Terraform Cloud做為目標、並可使用HTTP方法設定Terraform Cloud API。因此、工作流程可以結合使用一般API工作和其他作業來呼叫多個Terraform Cloud API的工作。您需要Premier授權才能使用ICO功能。



=== Cisco Intersight小幫手

Cisco Intersight協助可協助您將端點裝置新增至Cisco Intersight。資料中心可能有多個裝置無法直接與Cisco Intersight連線。Cisco Intersight支援但未直接連線至的任何裝置都需要連線機制。Cisco Intersight小幫手提供這種連線機制、可協助您將裝置新增至Cisco Intersight。

Cisco Intersight虛擬應用裝置可在Cisco Intersight虛擬應用裝置中使用Cisco Intersight輔助功能、此應用裝置以開放式虛擬應用裝置（OVA）檔案格式的可部署虛擬機器形式散佈。您可以在ESXi伺服器上安裝應用裝置。如需詳細資訊、請參閱 https://www.cisco.com/c/en/us/support/servers-unified-computing/intersight/products-installation-guides-list.html["Cisco Intersight Virtual Appliance入門指南"^]。

在Intersight中申請Intersight assist之後、您可以使用Intersight assist選項來申請端點裝置。如需詳細資訊、請參閱 https://intersight.com/help/getting_started["快速入門"^]。



== NetApp Cloud Volumes ONTAP

* 運用內建的重複資料刪除技術、資料壓縮、精簡配置及複製技術、將儲存成本降至最低。
* 在雲端環境發生故障時、提供企業級的可靠性和持續營運。
* NetApp SnapMirror是領先業界的複寫技術、可將內部部署的資料複寫到雲端、因此您可以輕鬆取得次要複本、以供多種使用案例使用。Cloud Volumes ONTAP
* 此外、還整合了支援備份與還原功能的功能、可保護雲端資料並長期歸檔。Cloud Volumes ONTAP Cloud Backup Service
* 在高效能與低效能儲存資源池之間隨需切換、而不需將應用程式離線。
* 使用NetApp SnapCenter 功能提供Snapshot複本的一致性。
* 支援資料加密、並提供防範病毒和勒索軟體的功能。 Cloud Volumes ONTAP
* 與Cloud Data Sense整合可協助您瞭解資料內容並識別敏感資料。




== Cloud Central

Cloud Central提供集中位置、可存取及管理NetApp雲端資料服務。這些服務可讓您在雲端上執行關鍵應用程式、建立自動化的DR站台、備份SaaS資料、以及在多個雲端之間有效地移轉和控制資料。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/occm35/concept_cloud_central.html["Cloud Central"^]。



== Cloud Manager

Cloud Manager是企業級SaaS型管理平台、可讓IT專家和雲端架構設計師使用NetApp雲端解決方案集中管理混合式多雲端基礎架構。它提供集中式系統、可用於檢視及管理內部部署與雲端儲存設備、以支援多家混合雲供應商與客戶。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/occm/index.html["Cloud Manager"^]。



== 連接器

Connector可讓Cloud Manager管理公有雲環境中的資源與程序。連接器執行個體必須使用Cloud Manager提供的許多功能、而且可以部署在雲端或內部部署網路中。下列位置支援連接器：

* AWS
* Microsoft Azure
* Google Cloud
* 內部部署




== NetApp Active IQ Unified Manager

NetApp Active IQ Unified Manager 功能可讓您透過ONTAP 重新設計的直覺式單一介面、監控您的不只是一個儲存叢集、還能提供社群智慧和AI分析的情報。它提供完整的作業、效能、以及對儲存環境及其上執行之虛擬機器的主動深入見解。當儲存基礎架構發生問題時、Unified Manager可通知您有關問題的詳細資料、以協助識別根本原因。虛擬機器儀表板可讓您檢視虛擬機器的效能統計資料、以便從vSphere主機到網路、最後到儲存設備的整個I/O路徑進行調查。

有些事件也提供補救行動、您可以採取這些行動來修正問題。您可以設定事件的自訂警示、以便在發生問題時、透過電子郵件和SNMP設陷通知您。利用NetApp可預測容量和使用趨勢、在發生問題之前主動採取行動、避免因應短期決策而導致長期的額外問題、藉此規劃使用者的儲存需求。Active IQ Unified Manager



== VMware vSphere

VMware vSphere是一套虛擬化平台、可將大量的基礎架構（包括CPU、儲存設備和網路等資源）、整體管理為無縫、多功能且動態的作業環境。與管理個別機器的傳統作業系統不同、VMware vSphere會將整個資料中心的基礎架構集合在一起、建立一個資源強大的單一儲存設備、以便快速動態地分配給任何需要的應用程式。

如需VMware vSphere的詳細資訊、請參閱 https://www.vmware.com/products/vsphere.html["此連結"^]。



== VMware vSphere vCenter

VMware vCenter Server可從單一主控台統一管理所有主機和VM、並集合叢集、主機和VM的效能監控。VMware vCenter Server可讓系統管理員深入瞭解運算叢集、主機、VM、儲存設備、來賓作業系統、 以及虛擬基礎架構的其他重要元件。VMware vCenter可管理VMware vSphere環境中的豐富功能集。



== 硬體與軟體版本

此混合雲解決方案可延伸至FlexPod 執行NetApp互通性對照表工具和Cisco UCS硬體相容清單所定義之受支援軟體、韌體和硬體版本的任何支援環境。

在內部部署環境中、用作基礎平台的功能就是根據所述的準則與規格來部署FlexPod https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmware_7u2.html["請按這裡"^]。

此環境中的網路為ACI型。如需詳細資訊、請參閱 https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9k_aci.html["請按這裡"^]。

* 如需詳細資訊、請參閱下列連結：
* http://support.netapp.com/matrix/["NetApp 互通性對照表工具"^]
* http://www.vmware.com/resources/compatibility/search.php["VMware相容性指南"^]
* https://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["Cisco UCS硬體與軟體互通性工具"^]


下表顯示FlexPod 了有關硬體與軟體版本的資訊。

|===
| 元件 | 產品 | 版本 


| 運算 | Cisco UCS X210 C-M6. | 5.0（1b） 


|  | Cisco UCS Fabric Interconnects 6454. | 4.2（2a） 


| 網路 | Cisco Nexus 9332C（脊柱） | 14.2（7秒） 


|  | Cisco Nexus 9336C-FX2（Leaf） | 14.2（7秒） 


|  | Cisco ACI | 4.2（7） 


| 儲存設備 | NetApp AFF 解決方案-A220 | 9.11.1. 


|  | 適用於VMware vSphere的NetApp ONTAP 產品開發工具 | 9.10. 


|  | 適用於VMware VAAI的NetApp NFS外掛程式 | 2.0-15 


|  | Active IQ Unified Manager | 9.11. 


| 軟體 | vSphere ESXi | 7.0（U3） 


|  | VMware vCenter應用裝置 | 7.0.3 


|  | Cisco Intersight輔助虛擬應用裝置 | 1.0.11-306 
|===
Terraform Cloud for Business帳戶會執行Terraform組態。Terraform組態使用Terraform供應商的NetApp Cloud Manager。

下表列出廠商、產品及版本。

|===
| 元件 | 產品 | 版本 


| HashiCorp | Terraform | 1.2.7 
|===
下表顯示Cloud Manager和Cloud Volumes ONTAP 各種版本的資訊。

|===
| 元件 | 產品 | 版本 


| NetApp | Cloud Volumes ONTAP | 9.11. 


|  | Cloud Manager | 3.9.21 
|===
link:gcp-ncvo-deploy-flexpod.html["下一步：安裝與組態-部署FlexPod 功能。"]
