---
sidebar: sidebar 
permalink: security/flexpod-fips-overview-of-fips-140-2.html 
keywords: fips 120-2, cryptographic module, security level, 
summary: FIPS 140-2指定了安全系統中用於保護電腦和電信系統中敏感資訊的密碼編譯模組安全性需求。 
---
= FIPS 140-2總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-cybersecurity-threats-in-healthcare.html["上一篇：醫療網路安全威脅。"]

[role="lead"]
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf["FIPS 140-2"^] 指定安全系統內用於保護電腦和電信系統中敏感資訊的密碼編譯模組安全需求。密碼編譯模組應為一組硬體、軟體、韌體或組合。FIPS適用於密碼編譯邊界內的密碼編譯演算法、金鑰產生和金鑰管理程式。請務必瞭解FIPS 140-2特別適用於密碼編譯模組、而非產品、架構、資料或生態系統。密碼編譯模組是本文件稍後以關鍵詞彙定義的元件（無論是硬體、軟體及/或韌體）、可實作核准的安全功能。此外、FIPS 140-2指定四個層級。核准的密碼編譯演算法適用於所有層級。每個安全層級的關鍵要素與要求包括：

* *安全等級1*
+
** 指定密碼編譯模組的基本安全需求（至少需要一個核准的演算法或安全功能）。
** 除了正式作業層級元件的基本需求之外、不需要針對層級1指定實體安全機制。


* *安全等級2*
+
** 透過使用防竄改解決方案（例如塗層或密封、可拆式機箱蓋或密碼模組門鎖）來增加防竄改證據的需求、進而強化實體安全機制。
** 至少需要角色型存取控制（RBAC）、密碼編譯模組會驗證操作者或管理員的授權、以承擔特定角色並執行一組對應的功能。


* *安全等級3*
+
** 建置於層級2的防竄改要求之上、並嘗試防止進一步存取密碼編譯模組內的關鍵安全參數（CSP）。
** 第3級所需的實體安全機制、是為了能夠偵測並回應實體存取嘗試、或是密碼編譯模組的任何使用或修改。例如強式機箱、竄改偵測和回應電路、可在密碼編譯模組上開啟卸除式機箱蓋時、將所有純文字CSP歸零。
** 需要身分識別型驗證機制、以強化第2層所指定之RBAC機制的安全性。密碼編譯模組會驗證操作員的身分、並驗證操作員是否有權使用角色並執行角色的功能。


* *安全等級4*
+
** FIPS 140-2的最高安全等級。
** 最適合實體無保護環境中的作業層級。
** 在此層級、實體安全機制旨在提供密碼編譯模組的完整保護、以偵測及回應任何未獲授權的實體存取嘗試。
** 密碼編譯模組的滲透或曝險應具有很高的偵測機率、並導致所有不安全或純文字CSP立即歸零。




link:flexpod-fips-control-plane-versus-data-plane.html["下一步：控制面與資料面。"]
