---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-deploy_design.html 
keywords: architecture, storage, layout, aggregates, database, disk, type, control, failover, hardware, aff 
summary: MEDITECH的架構FlexPod 以MEDITECH、Cisco和NetApp的指引為基礎、並以合作夥伴與各種規模的MEDITECH客戶合作的經驗為基礎。此架構可靈活調整、並根據您的資料中心策略、組織規模、以及您的系統是否為集中式、分散式或多租戶、套用MEDITECH的最佳實務做法。 
---
= 設計
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
MEDITECH的架構FlexPod 以MEDITECH、Cisco和NetApp的指引為基礎、並以合作夥伴與各種規模的MEDITECH客戶合作的經驗為基礎。此架構可靈活調整、並根據您的資料中心策略、組織規模、以及您的系統是否為集中式、分散式或多租戶、套用MEDITECH的最佳實務做法。

正確的儲存架構可由整體大小和IOPS總計來決定。效能不只是唯一的考量因素、您可能會根據其他客戶需求決定使用較大的節點數。使用NetApp儲存設備的優勢在於、您可以輕鬆且不中斷營運地隨需求變化而擴充叢集。您也可以在不中斷營運的情況下、從叢集中移除節點、以重新規劃設備用途、或在設備更新期間移除節點。

以下是NetApp ONTAP 解決方案儲存架構的一些優點：

* *易用、不中斷營運的垂直擴充和橫向擴充。*您可以使用ONTAP 不中斷營運的功能來升級、新增或移除磁碟和節點。您可以從四個節點開始、移至六個節點、或在不中斷營運的情況下升級至較大的控制器。
* *儲存效率。*利用重複資料刪除技術、NetApp FlexClone、即時壓縮、即時壓縮、精簡複寫、 資源隨需配置、以及集合式重複資料刪除技術。FlexClone功能可讓您幾乎立即建立複本、以支援備份與測試環境更新。這些複本只會隨著變更而耗用更多儲存空間。
* *災難恢復陰影資料庫伺服器。*災難恢復陰影資料庫伺服器是您營運不中斷策略的一部分（用於支援儲存唯讀功能、並可能設定為儲存讀寫執行個體）。因此、第三個儲存系統的放置與規模調整通常與正式作業資料庫儲存系統相同。
* *資料庫一致性（需要考量）。*如果您使用NetApp SnapMirror備份複本來維持營運不中斷、請參閱 http://media.netapp.com/documents/tr-3446.pdf["TR-3446：SnapMirror非同步概述與最佳實務做法指南"^]。




== 儲存配置



=== 專屬的MEDITECH主機Aggregate

為了滿足MEDITECH的高效能與高可用度需求、第一步是正確設計MEDITECH環境的儲存配置、將MEDITECH主機正式作業工作負載隔離至專屬的高效能儲存設備。

每個儲存控制器都應配置一個專屬的Aggregate、以儲存MEDITECH主機的程式、目錄和資料檔案。為了避免使用相同磁碟的其他工作負載影響效能、這些集合體中不會配置其他儲存設備。


NOTE: 您為其他MEDITECH伺服器配置的儲存設備、不應放置在MEDITECH主機所使用LUN的專屬集合體上。您應該將其他MEDITECH伺服器的儲存設備放在個別的集合體上。其他MEDITECH伺服器的儲存需求可在「硬體組態提案」（適用於新部署）和「硬體評估工作」（適用於現有部署）文件中找到。您可以透過MEDITECH系統整合商或MEDITECH技術客戶經理（TAM）、向MEDITECH索取這些文件。NetApp解決方案工程師可能會諮詢NetApp MEDITECH Independent Software Vendor（ISV）團隊、以協助建立適當且完整的NetApp儲存設備規模設定。



=== 將MEDITECH主機工作負載平均分散到所有儲存控制器

NetApp FAS 的功能與AFF 功能是以一或多個高可用度配對來部署。NetApp建議您在每個儲存控制器上平均分散MEDITECH的廣大範圍和6.x工作負載、以便在每個儲存控制器上套用運算、網路和快取資源。

請使用下列準則、將MEDITECH工作負載平均分散到每個儲存控制器：

* 如果您知道每部MEDITECH主機的IOPS、您可以確認每個控制器從MEDITECH主機提供的IOPS數量類似、將MEDITECH的範圍和6.x工作負載平均分散到所有儲存控制器。
* 如果您不知道每部MEDITECH主機的IOPS、您仍可將MEDITECH的範圍和6.x工作負載平均分散到所有儲存控制器。確認MEDITECH主機的集合體容量平均分散於所有儲存控制器、以完成此工作。如此一來、專屬MEDITECH主機的所有資料集合體的磁碟數量都相同。
* 使用類似的磁碟類型和相同的RAID群組、建立兩個控制器的儲存集合體、以平均分配工作負載。建立儲存Aggregate之前、請先聯絡NetApp認證整合商。



NOTE: 據MEDITECH所述、MEDITECH系統中的兩個主機所產生的IOPS比其他主機高。這兩個主機的LUN應放置在不同的儲存控制器上。在部署系統之前、您應該先在MEDITECH團隊的協助下識別這兩個主機。



== 儲存設備放置



=== MEDITECH主機的資料庫儲存設備

MEDITECH主機的資料庫儲存設備是以區塊設備（即LUN）形式呈現、來自NetApp FAS 的整套系統。AFFLUN通常以E磁碟機的形式掛載至Windows作業系統。



=== 其他儲存設備

MEDITECH主機作業系統和資料庫應用程式通常會在儲存設備上產生大量的IOPS。必要時、MEDITECH主機VM及其VMDK檔案的儲存資源配置被視為獨立於符合MEDITECH效能臨界值所需的儲存設備。

為其他MEDITECH伺服器配置的儲存設備、不應放在MEDITECH主機所使用LUN的專屬集合體上。將其他MEDITECH伺服器的儲存設備放在獨立的集合體上。



== 儲存控制器組態



=== 高可用度

若要減輕控制器故障的影響、並啟用儲存系統的不中斷升級、您應該在高可用度模式下、將儲存系統的控制器設定為高可用度配對。

使用高可用度控制器配對組組態時、磁碟櫃應透過多個路徑連接至控制器。此連線可防止單一路徑故障、進而提升儲存恢復能力、並在發生控制器容錯移轉時改善效能一致性。



=== 儲存控制器容錯移轉期間的儲存效能

對於以高可用度配對組設定控制器的儲存系統、在控制器發生故障的可能性不大的情況下、合作夥伴控制器會接管故障控制器的儲存資源和工作負載。請務必洽詢客戶、以確定控制器故障時必須符合的效能要求、並據此調整系統規模。



=== 硬體輔助接管

NetApp建議您在兩個儲存控制器上開啟硬體輔助接管功能。

硬體輔助接管的設計旨在將儲存控制器的容錯移轉時間減至最低。它可讓一個控制器的遠端LAN模組或服務處理器模組、以比活動訊號逾時觸發更快的速度通知合作夥伴、縮短容錯移轉所需的時間。在高可用度組態中、儲存控制器預設會啟用硬體輔助接管功能。

如需硬體輔助接管的詳細資訊、請參閱 http://docs.netapp.com/ontap-9/index.jsp["供應說明文件中心 ONTAP"^]。



=== 磁碟類型

為支援MEDITECH工作負載的低讀取延遲需求、NetApp建議您使用高效能SSD、將專AFF 為MEDITECH主機所設計的VMware系統集合在一起。



=== NetApp AFF

NetApp提供高效能AFF 的支援、以因應需要高處理量、隨機資料存取模式和低延遲需求的MEDITECH工作負載。針對MEDITECH工作負載、AFF 與採用HDD的系統相比、ESITECH陣列提供更高的效能優勢。Flash技術與企業資料管理的結合、可在效能、可用度和儲存效率等三大領域提供優勢。



=== NetApp支援工具與服務

NetApp提供完整的支援工具與服務。如果AutoSupport 發生硬體故障或系統組態錯誤、應在NetApp AFF/FAS系統上啟用並設定NetApp支援工具、以便撥打住家電話。主叫提醒NetApp支援團隊及時修正任何問題。NetApp Active IQ 功能是一種網路應用程式、以AutoSupport NetApp系統的各種資訊為基礎、提供預測性和主動式洞察、協助提升可用度、效率和效能。
