---
sidebar: sidebar 
permalink: healthcare/ehr-epic-deploy_cisco_ucs_blade_server_and_switch_configuration.html 
keywords: cisco, ucs, blade, server, switch, configuration 
summary: 《Epic適用的解決方案FlexPod 」軟體是專為每個層級的容錯設計。系統中沒有單點故障。本文件旨在針對FlexPod Epic軟體的基本組態、提供深入的指引。 
---
= Cisco UCS刀鋒伺服器與交換器組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


《Epic適用的解決方案FlexPod 」軟體是專為每個層級的容錯設計。系統中沒有單點故障。我們建議使用熱備援刀鋒伺服器、以獲得最佳效能。

本文件旨在針對FlexPod Epic軟體的基本組態、提供深入的指引。在本節中、我們提供一些高階步驟、以及一些範例、協助您準備FlexPod 好支援此功能的Cisco UCS運算平台元素。本指南的先決條件是FlexPod 、根據FlexPod 《利用FC儲存設備的非資料中心》中的指示、以機架安裝、供電及纜線方式連接整個系統。



== Cisco Nexus交換器組態

為解決方案部署了Cisco Nexus 9300系列乙太網路交換器的容錯配對。這些交換器應依照一節所述進行纜線連接 link:ehr-epic-deploy_deployment_and_configuration_overview.html#cabling-diagram["「佈線圖」。"] Cisco Nexus組態可確保乙太網路流量傳輸已針對Epic應用程式最佳化。

. 完成初始設定與授權之後、請執行下列命令、在兩個交換器上設定全域組態參數：
+
....
spanning-tree port type network default
spanning-tree port type edge bpduguard default
spanning-tree port type edge bpdufilter default
port-channel load-balance src-dst l4port
ntp server <global-ntp-server-ip> use-vrf management
ntp master 3
ip route 0.0.0.0/0 <ib-mgmt-vlan-gateway>
copy run start
....
. 使用全域組態模式在每台交換器上建立解決方案的VLAN：
+
....
vlan <ib-mgmt-vlan-id>
name IB-MGMT-VLAN
vlan <native-vlan-id>
name Native-VLAN
vlan <vmotion-vlan-id>
name vMotion-VLAN
vlan <vm-traffic-vlan-id>
name VM-Traffic-VLAN
vlan <infra-nfs-vlan-id>
name Infra-NFS-VLAN
exit
copy run start
....
. 建立NTP發佈介面、連接埠通道、連接埠通道參數和連接埠說明、以便根據進行疑難排解 https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi65u1_n9fc.html["採用FC Cisco驗證設計的資料中心FlexPod"^]。


link:ehr-epic-deploy_esxi_configuration_best_practices.html["下一步：ESXi組態最佳實務做法"]
