---
sidebar: sidebar 
permalink: healthcare/ehr-epic-deploy_netapp_configuration.html 
keywords: configuration, ha, pair, configuration, storage, fc, protocol, flexpod, epic 
summary: 針對Epic軟體環境部署的NetApp儲存設備使用高可用度（HA）配對組態的儲存控制器。儲存設備必須透過FC傳輸協定（FCP）從兩個控制器呈現給Epic資料庫伺服器。 
---
= NetApp組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


針對Epic軟體環境部署的NetApp儲存設備使用高可用度（HA）配對組態的儲存控制器。儲存設備必須透過FC傳輸協定（FCP）從兩個控制器呈現給Epic資料庫伺服器。此組態會顯示兩個控制器的儲存設備、以便在正常作業期間平均平衡應用程式負載。

Epic All Flash參考架構策略手冊詳細說明將正式作業工作負載分成故障網域呼叫集區的嚴苛要求。請先詳閱本文件、再繼續。請注意ONTAP 、可以將某個節點視為獨立的儲存資源池。



== 組態ONTAP

本節說明使用相關ONTAP 的指令之部署和資源配置程序的範例。重點在於說明如何配置儲存設備、以實作NetApp建議的儲存配置、這種配置使用HA控制器配對。利用NetApp的主要優勢之一ONTAP 、就是能夠在不干擾現有HA配對的情況下進行橫向擴充。

EPIC為每位客戶提供詳細的儲存效能需求和配置指引、包括儲存簡報和主機端儲存配置。Epic將提供下列自訂文件：

* Epic Hardware Configuration Guide（Epic硬體組態指南）、用於在售前期間調整規模。
* Epic資料庫儲存配置建議用於部署期間的LUN和Volume配置。


客戶專屬的儲存系統配置與組態必須參考Epic資料庫儲存配置建議、才能符合這些需求。

以下範例說明AFF 如何部署支援10TB資料庫的支援功能。下表顯示範例部署中用於支援正式作業資料庫的儲存設備資源配置參數。

|===
| 參數 | 控制器1 | 控制器2 


| 控制器主機名稱 | 產品1-01. | 產品1-02. 


| Aggregate ONTAP | Aggr0_prod1-01（ADP 11個分割區） | aggr0_prod1-02（ADP 11個分割區） 


| 集合體資料 | 產品1-01_aggr1（22個分割區） | 產品1-02_aggr1（22個分割區） 


| Volume（大小） | EPIC PROD_DB1（2TB）EPIC PROD_DB2（2TB）EPIC PROD_DB3（2TB）EPIC PROD_DB4（2TB）EPIC PROD_DB5（2TB）EPIC PROD_DB6（2TB）EPIC _PROD_DB7（2TB）EPIC PROD_DB8（2TB）EPIC _PROD_PROD_DB8（2TB）1EPIC（1TB）_PRO_PRO_PRO_N1st_PRO_PRO_PRO_PRO_PRO_N1EPIC）1（1TB）（1TB）（1TB）（1st_PRO_PRO_PRO_PRO_PRO_PRO_PRO_PRO | EPIC報告_db1（2TB）EPIC報告_DB2（2TB）EPIC報告_db3（2TB）EPIC報告_db4（2TB）EPIC報告_DB5（2TB）EPIC報告_db6（2TB）EPIC報告_DB7（2TB）EPIC報告_db8（2TB）EPIC報告_inst（1TB）EPIC報告_report_db2（2TB）jrEpic報告_jrEpic報告_1200GB） 


| LUN路徑（大小） | /ePIC prod_db1/ePIC prod_db1（1.4TB）/ePIC prod_db2/ePIC prod_pod_stg（1.4TB）/ePIC _prod_db3（1.4TB）/ePIC _prod_db4/ePIC prod_db4（1.4TB）/ePIC _prost_ePIC /st_ePIC）/4d_rost_ePIC 4d_rost_ePIC 4d_pro_nst_ePIC（4k_ePIC）/4d_st_ePIC）/4d_projePIC 4d_st_ePIC）/4d_projePIC 4d_st_st_rost_ePIC 4k_prop_projePIC 4k_pro_4k_4k_4k_pro_4k_4k_4k_4k_prop_nst_4k_projrod_4k_4k_4k_prope_nst_4d_4k_4d_4k_4k_4k_je | /EPIC PROD_db1/EPIC報告_db1（1.4TB）/EPIC PROd_db2/EPIC report_db2（1.4TB）/EPIC _prod_db3/EPIC report_db3（1.4TB）/EPIC _prod_db4/EPIC報告_report_db4（1.4TB）/EPIC _prod_db5/EPIC DB_st_ePIC報告（164k_nst_ePIC）/ePIC）/4k_jePIC報告）/jePIC）/4k_jst_ePIC報告（4k_ePIC）/jePIC）/ePIC）/4k_st_ePIC報告（4d_ePIC）/jePIC）/jst_ePIC）/4k_ePIC報告（16（16（16）/4k_ePIC）/4k_jePIC）/4k_ePIC）/4k_jePIC）/4k_st_ePIC）/ePIC）/4d_ePIC）/j 


| VM | RHEL | RHEL 


| LUN類型 | Linux（以RDM形式安裝、直接由RHEL VM使用FC安裝） | Linux（以RDM形式安裝、直接由RHEL VM使用FC安裝） 


| FCP啟動器群組（igroup）名稱 | IG_EPIC PROD（Linux） | IG_EPIC報告（Linux） 


| 主機作業系統 | VMware | VMware 


| EPIC資料庫伺服器主機名稱 | EPIC PROD | EPIC報告 


| SVM | SVM_Prod | SVM_ps（正式作業服務）SVM_CIFS 
|===


=== 不需要授權ONTAP

設定儲存控制器之後、請套用授權以啟用ONTAP NetApp建議的功能。Epic工作負載所需的授權包括FC、CIFS、Snapshot、SnapRestore 和SnapMirror。

若要套用授權、請開啟NetApp System Manager、移至「組態授權」並新增適當的授權。或者、也可以執行下列命令、使用CLI新增授權：

....
license add -license-code <code>
....


=== 組態AutoSupport

此功能可透過HTTPS將摘要支援資訊傳送給NetApp。AutoSupport若要設定AutoSupport 靜態、請執行下列ONTAP 指令：

....
autosupport modify -node * -state enable
autosupport modify -node * -mail-hosts <mailhost.customer.com>
autosupport modify -node prod1-01 -from prod1-01@customer.com
autosupport modify -node prod1-02 -from prod1-02@customer.com
autosupport modify -node * -to storageadmins@customer.com
autosupport modify -node * -support enable
autosupport modify -node * -transport https
autosupport modify -node * -hostnamesubj true
....


=== 硬體輔助接管組態

在每個節點上、啟用硬體輔助接管功能、以將控制器不太可能發生故障後啟動接管所需的時間減至最低。若要設定硬體輔助接管、請完成下列步驟：

. 執行下列ONTAP 指令。將合作夥伴位址選項設定為prod1-01管理連接埠的IP位址。
+
....
EPIC::> storage failover modify -node prod1-01 -hwassist-partner-ip <prod1-02-mgmt-ip>
....
. 執行下列ONTAP 指令。將合作夥伴位址選項設定為叢集1至02的管理連接埠IP位址。
+
....
EPIC::> storage failover modify -node prod1-02 -hwassist-partner-ip <prod1-01-mgmt-ip>
....
. 執行下列ONTAP 支援功能、在Prod1-01和prod1-02 HA控制器配對上啟用硬體輔助接管：
+
....
EPIC::> storage failover modify -node prod1-01 -hwassist true
EPIC::> storage failover modify -node prod1-02 -hwassist true
....




=== 儲存資源配置ONTAP

儲存資源配置工作流程如下：

. 建立集合體。
. 建立儲存虛擬機器（SVM）。
+
建立Aggregate之後、下一步是建立SVM。在本例中、儲存設備會以SVM的形式進行虛擬化。ONTAP主機和用戶端不再存取實體儲存硬體。使用System Manager GUI或CLI建立SVM。

. 建立FC LIF。
+
連接埠和儲存設備是在SVM上配置、並透過稱為邏輯介面（lifs）的虛擬連接埠呈現給主機和用戶端。

+
您可以在單一SVM中以所有的傳輸協定執行所有工作負載。對於Epic、NetApp建議使用SVM進行正式作業FC、並使用一部SVM進行CIFS。

+
.. 從System Manager GUI中的SVM設定啟用和啟動FC。
.. 新增FC LIF至SVM。根據每個LUN架構的路徑數量、在每個儲存節點上設定多個FC生命量。


. 建立啟動器群組（igroup）。
+
igroup是FC傳輸協定主機WWPN或iSCSI主機節點名稱的表格、可定義主機可用的LUN。例如、如果您有主機叢集、可以使用igroup來確保叢集中的一部主機或叢集中的所有主機都能看到特定的LUN。您可以定義多個igroup並將其對應至LUN、以控制哪些啟動器可以存取LUN。

+
使用System Manager GUI或CLI建立類型為VMware的FC igroup。

. 在FC交換器上建立區域。
+
FC或FCoE區域是一個或多個連接埠的邏輯群組、位於一個網路架構中。為了讓裝置能夠彼此查看、連線、建立彼此的工作階段、以及進行通訊、這兩個連接埠都必須具有通用的區域成員資格。建議使用單一啟動器分區。

+
.. 在交換器上建立區域、並在區域中新增NetApp目標和Cisco UCS刀鋒啟動器。
+
NetApp最佳實務做法是單一啟動器分區。每個區域在控制器上只包含一個啟動器和目標WWPN。區域使用連接埠名稱、而非節點名稱。



. 建立磁碟區和LUN。
+
.. 使用System Manager GUI（或CLI）建立磁碟區以裝載LUN。所有的儲存效率設定和資料保護都是在磁碟區上預設設定的。您可以選擇使用「volmodify」命令、在磁碟區上開啟磁碟區加密和QoS原則。請注意、磁碟區必須夠大、才能容納LUN和Snapshot複本。若要保護磁碟區免受容量問題的影響、請啟用「autodsize」和「autodete」選項。建立磁碟區之後、請建立容納Epic工作負載的LUN。
.. 使用System Manager GUI（或CLI）建立類型為「VMware」的FC LUN、以裝載Epic工作負載。NetApp已在System Manager中的易於遵循的精靈中簡化LUN的建立。
+
您也可以使用VSC來配置磁碟區和LUN。請參閱 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-fc-esx-cpg/home.html["《ESX Express FC組態指南》"^]。

+
請參閱 http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-sanag%2Fhome.html["SAN管理與SAN組態指南"^] 如果您不使用VSC。



. 將LUN對應至igroup。
+
在建立LUN和igroup之後、將LUN對應至相關的igroup、以便讓所需的主機存取LUN。

+
現在、LUN已準備好可供探索並對應至ESXi伺服器。重新整理ESXi主機上的儲存設備、並新增新發現的LUN。



link:ehr-epic-deploy_genio_tool.html["下一步：Genio工具。"]
