---
sidebar: sidebar 
permalink: healthcare/ehr-meditech-sizing_meditech_workload_overview.html 
keywords: meditech, workload, backup, cisco, ucs, reference, architecture, platforms 
summary: 本節說明您可能在MEDITECH環境中找到的運算和儲存工作負載類型。 
---
= Meditech工作負載總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
本節說明您可能在MEDITECH環境中找到的運算和儲存工作負載類型。



== Meditech與備份工作負載

當您針對MEDITECH環境調整NetApp儲存系統規模時、必須同時考量MEDITECH的正式作業工作負載和備份工作負載。

|===
| Meditech主持人 


| MEDITECH主機是資料庫伺服器。此主機也稱為MEDITECH檔案伺服器（適用於廣闊平台、6.x或C/S 5.x平台）或魔術機器（適用於魔術平台）。本文使用「MEDITECH主機」一詞來指稱MEDITECH檔案伺服器和一台魔力機器。 
|===
以下各節將說明這兩項工作負載的I/O特性和效能需求。



== Meditech工作負載

在MEDITECH環境中、執行MEDITECH軟體的多部伺服器會以稱為MEDITECH系統的整合式系統來執行各種工作。如需MEDITECH系統的詳細資訊、請參閱MEDITECH文件：

* 對於正式作業的MEDITECH環境、請參閱適當的MEDITECH文件、以判斷MEDITECH主機的數量、以及在調整NetApp儲存系統規模時必須納入的儲存容量。
* 如需新的MEDITECH環境、請參閱硬體組態提案文件。如需現有的MEDITECH環境、請參閱硬體評估工作文件。硬體評估工作與MEDITECH Ticket相關。客戶可向MEDITECH索取上述任一文件。


您可以擴充MEDITECH系統、藉由新增主機來提高容量和效能。每個主機的資料庫和應用程式檔案都需要儲存容量。每個MEDITECH主機可用的儲存設備也必須支援主機所產生的I/O。在MEDITECH環境中、每個主機都有一個LUN可用來支援該主機的資料庫和應用程式儲存需求。MEDITECH類別的類型和您部署的平台類型、決定了每個MEDITECH主機的工作負載特性、因此也決定了整個系統的工作負載特性。



=== Meditech類別

Meditech將部署規模與1到6之間的類別編號建立關聯。第1類是最小的MEDITECH部署；第6類是最大的部署。與每個類別相關的MEDITECH應用程式規格範例包括以下指標：

* 醫院病牀數量
* 每年住院病患數
* 每年超過病患
* 每年進行急診室訪視
* 每年考試數
* 每天的住院處方
* 每天的門診處方


如需MEDITECH類別的詳細資訊、請參閱MEDITECH類別參考表。您可以透過客戶或MEDITECH系統安裝程式、從MEDITECH取得這份工作表。



=== Meditech平台

Meditech有四種平台：

* 廣闊
* Meditech 6.x
* 用戶端/伺服器5.x（C/S 5.x）
* 魔法


對於MEDITECH的整個、6.x和C/S 5.x平台、每個主機的I/O特性定義為100%隨機、要求大小為4、000。對於MEDITECH的魔力平台、每個主機的I/O特性定義為100%隨機、要求大小為8、000或16、000。據MEDITECH所述、典型魔力正式作業部署的申請規模為8、000或16、000。

讀取和寫入的比率會因部署的平台而異。Meditech估計讀寫的平均混合比例、然後以百分比表示。Meditech也預估特定MEDITECH平台上每部MEDITECH主機所需的平均持續IOPS值。下表摘要說明MEDITECH所提供的平台特定I/O特性。

|===
| Meditech類別 | Meditech平台 | 平均隨機讀取% | 平均隨機寫入% | 每個MEDITECH主機平均持續IOPS 


| 1. | 廣寬、6.x | 20 | 80 | 750 


.4+| 2-6. | 廣闊 | 20 | 80 | 750 


| 6.x | 20 | 80 | 750 


| C/S 5.x | 40 | 60 | 600 


| 魔法 | 90 | 10. | 400 
|===
在MEDITECH系統中、每個主機的平均IOPS層級必須等於上表中定義的IOPS值。為了根據每個平台判斷正確的儲存規模、上表中指定的IOPS值將作為中所述規模調整方法的一部分使用 link:ehr-meditech-sizing_technical_specifications_for_small,_medium_and_large_architectures.html["小型、中型和大型架構的技術規格"] 區段。

Meditech要求每個主機平均隨機寫入延遲低於1毫秒。不過、在備份和重新分配工作期間、暫時增加寫入延遲達2毫秒、是可以接受的做法。Meditech也需要平均隨機讀取延遲、才能維持在第1類主機低於7毫秒、第2類主機低於5毫秒。無論使用何種MEDITECH平台、這些延遲需求都適用於每個主機。

下表摘要說明當您調整NetApp儲存設備以處理MEDITECH工作負載時、必須考量的I/O特性。

|===
| 參數 | Meditech類別 | 廣闊 | Meditech 6.x | C/S 5.x | 魔法 


| 要求大小 .2+| 1-6 | 4K | 4K | 4K | 8K或16K 


| 隨機/連續 | 100%隨機 | 100%隨機 | 100%隨機 | 100%隨機 


.2+| 平均持續IOPS | 1. | 750 | 750 | 不適用 | 不適用 


| 2-6. | 750 | 750 | 600 | 400 


| 讀寫比率 .2+| 1-6 | 20%讀取、80%寫入 | 20%讀取、80%寫入 | 40%讀取、60%寫入 | 90%讀取、10%寫入 


| 寫入延遲 | 不到1毫秒 | 不到1毫秒 | 不到1毫秒 | 不到1毫秒 


| 暫用尖峰寫入延遲 | 1-6 | 低於2毫秒 | 低於2毫秒 | 低於2毫秒 | 低於2毫秒 


.2+| 讀取延遲 | 1. | 低於7毫秒 | 低於7毫秒 | 不適用 | 不適用 


| 2-6. | 低於5毫秒 | 低於5毫秒 | 低於5毫秒 | 低於5毫秒 
|===

NOTE: 第3類至第6類的Meditech主機具有與第2類相同的I/O特性。對於MEDITECH類別2至6、每個類別中部署的主機數量各不相同。

NetApp儲存系統的規模應能滿足前幾節所述的效能要求。除了MEDITECH正式作業工作負載之外、NetApp儲存系統必須能夠在備份作業期間維持這些MEDITECH效能目標、如下節所述。



== 備份工作負載說明

Meditech認證的備份軟體可備份MEDITECH系統中每個MEDITECH主機所使用的LUN。為了讓備份處於應用程式一致的狀態、備份軟體會使MEDITECH系統靜止、並暫停磁碟的I/O要求。當系統處於靜止狀態時、備份軟體會發出命令給NetApp儲存系統、以建立包含LUN之磁碟區的NetApp Snapshot複本。備份軟體稍後會停止MEDITECH系統、讓正式作業I/O要求能夠繼續存取資料庫。該軟體會根據Snapshot複本建立NetApp FlexClone Volume。備份來源會使用此磁碟區、而正式作業I/O要求則會在主控LUN的父磁碟區上繼續執行。

備份軟體產生的工作負載來自於FlexClone磁碟區中LUN的連續讀取。工作負載定義為100%循序讀取工作負載、要求大小為64000。對於MEDITECH正式作業工作負載、效能標準是維持所需的IOPS及相關的讀寫延遲層級。不過、對於備份工作負載、備份作業期間所產生的整體資料處理量（Mbps）會轉移注意力。Meditech LUN備份必須在八小時的備份時間內完成、但NetApp建議您在六小時內完成所有MEDITECH LUN的備份。針對非計畫性增加的MEDITECH工作負載、NetApp ONTAP 支援的背景作業、或隨著時間而增加的資料等事件、我們的目標是在六小時內完成備份。任何這些事件都可能需要額外的備份時間。無論儲存的應用程式資料量為何、備份軟體都會針對每個MEDITECH主機、對整個LUN執行完整的區塊層級備份。

根據其他相關因素、計算完成此視窗內備份所需的連續讀取處理量：

* 所需的備份時間
* LUN數量
* 要備份的每個LUN大小


例如、在每個主機LUN大小為200GB的50台主機MEDITECH環境中、要備份的LUN總容量為10TB。

若要在八小時內備份10TB的資料、需要下列處理量：

* =（10 x 10^6）MB（8 x 3、600）s
* = 347.2MBps


不過、為了因應非計畫性事件、我們選擇了5.5小時的保守備份時間、以提供超過建議時間六小時的保留空間。

若要在八小時內備份10TB的資料、需要下列處理量：

* =（10 x 10^6）MB（5.5 x 3、600）s
* = 500Mbps


以500Mbps的處理量速度、備份可在5.5小時內完成、而且在8小時的備份需求範圍內也能輕鬆完成。

下表摘要說明當您調整儲存系統時、要使用的備份工作負載I/O特性。

|===
| 參數 | 所有平台 


| 要求大小 | 64K 


| 隨機/連續 | 100%連續 


| 讀寫比率 | 100%讀取 


| 平均處理量 | 取決於MEDITECH主機的數量和每個LUN的大小：備份必須在8小時內完成。 


| 必要的備份持續時間 | 8小時 
|===


== 適用於MEDITECH的Cisco UCS參考架構

MEDITECH on FlexPod ESI方面 的架構是以MEDITECH、Cisco和NetApp的指引為基礎、並以合作夥伴與各種規模的MEDITECH客戶合作的經驗為基礎。此架構可隨客戶的資料中心策略而調整、並套用MEDITECH的最佳實務做法：無論是小型或大型、集中式、分散式或多租戶。

部署MEDITECH時、Cisco設計的Cisco UCS參考架構直接符合MEDITECH的最佳實務做法。Cisco UCS提供緊密整合的解決方案、提供高效能、高可用度、可靠性及擴充性、可支援數千張病牀的醫師實務做法和醫院系統。
