---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: Cisco 驗證的設計包括經過設計、測試及記錄的系統與解決方案、以利並改善客戶部署。 
---
= 採用Oracle RAC資料庫的Datacenter搭配Cisco UCS和NetApp解決方案A系列FlexPod AFF
:allow-uri-read: 


Tushar Patel 、 Cisco Hardikkumar Vyas 、 Cisco

[role="lead"]
Cisco 驗證的設計包括經過設計、測試及記錄的系統與解決方案、以利並改善客戶部署。這些設計將廣泛的技術和產品整合到一系列解決方案中、這些解決方案是為了滿足客戶的業務需求而開發的。Cisco 與 NetApp 合作提供 FlexPod 、作為各種工作負載的基礎、並根據客戶需求、實現高效率的架構設計。FlexPod 解決方案是一種經過驗證的方法、可將 Cisco 和 NetApp 技術部署為共享雲端基礎架構。

FlexPod Datacenter 與 NetApp All Flash AFF 系統是一種融合式基礎架構平台、結合了 Cisco 和 NetApp 的頂尖技術、成為適用於企業應用程式的強大整合式平台。Cisco 和 NetApp 與 Oracle 密切合作、支援現今企業所需的要求最嚴苛的交易和回應時間敏感資料庫。

此 Cisco 驗證設計（ CVD ）說明使用 Cisco UCS 和 NetApp All Flash AFF 儲存設備來部署高可用度 Oracle RAC 資料庫環境的參考 FlexPod 資料中心架構。本文件說明所涉及元件的硬體和軟體組態、以及各種測試的結果。此外、本文件也提供使用 Cisco UCS 運算伺服器、 Cisco Fabric 互連交換器、 Cisco MDS 交換器、 Cisco Nexus 交換器、 NetApp AFF 儲存設備和 Oracle RAC 資料庫的實作與最佳實務指引。

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["採用Oracle RAC資料庫的Datacenter搭配Cisco UCS和NetApp解決方案A系列FlexPod AFF"^]
