---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: 檢查您是否符合與ONTAP Cisco Intersight整合NetApp®儲存設備的硬體、軟體及授權要求。 
---
= 需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
驗證您是否符合 NetApp ONTAP 儲存設備與 Cisco Intersight 整合的硬體、軟體和授權要求。



== 硬體與軟體需求

這些是實作解決方案所需的最低硬體和軟體元件。在解決方案的任何特定實作中使用的元件、可能會因客戶需求而異。

|===
| 元件 | 需求詳細資料 


| NetApp ONTAP | 部分9.7P1及更新版本ONTAP 


| NetApp Active IQ Unified Manager | 需要最新版本的 NetApp Active IQ Unified Manager （目前為 9.14RC1 ） 


| NetApp儲存陣列 | ONTAP 9.7P1 及更新版本支援的所有 ONTAP ASA 、 AFF 及 FAS 儲存陣列 


| 虛擬化Hypervisor | vSphere 7.0 及更新版本 
|===

NOTE: 請參閱 https://intersight.com/help/saas/supported_systems["Cisco Intersight 支援的系統"^] 適用於Cisco UCS運算元件和UCSM版本的最低需求。



== Cisco Intersight授權要求

Cisco Intersight 提供基礎架構服務和 Cloud Orchestrator 服務等服務、以管理、自動化及最佳化實體儲存設備（ NetApp 儲存設備）。您可以使用這些服務來管理 Cisco UCS 伺服器和 Cisco HyperFlex 系統。基礎架構服務和 Cloud Orchestrator 服務使用多層的訂閱型授權模式。您可以選擇所選訂閱期間所需的 Cisco UCS Server Volume 層級。

.授權模式
Cisco Intersight Infrastructure Services 授權模式已簡化、現在提供下列兩層：

* * Cisco Intersight Infrastructure Services Essentials * ： Essentials 授權層提供伺服器管理功能、包括全球健全狀況監控功能、庫存、透過 Cisco TAC 整合提供主動式支援、多重驗證、以及提供 SDK 和 API 存取。
* * Cisco Intersight Infrastructure Services Advantage* ：「優勢」授權層提供進階伺服器管理功能、提供更高的可見度、生態系統整合、 Cisco 與協力廠商軟硬體的自動化、以及提供多網域解決方案。


如需各種授權層級所涵蓋功能的詳細資訊、請參閱 https://intersight.com/help/saas/getting_started/licensing_requirements/lic_infra#licensing_model["基礎架構服務授權"^]。
