---
sidebar: sidebar 
permalink: ontap-connector-for-intersight/ci-qsg_requirements.html 
keywords: netapp, ontap, cisco, intersight, hardware, software, licensing, requirements 
summary: 檢查您是否符合與ONTAP Cisco Intersight整合NetApp®儲存設備的硬體、軟體及授權要求。 
---
= 需求
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
檢查您是否符合與ONTAP Cisco Intersight整合NetApp®儲存設備的硬體、軟體及授權要求。



== 硬體與軟體需求

這些是實作解決方案所需的最低硬體和軟體元件。在解決方案的任何特定實作中使用的元件、可能會因客戶需求而異。

|===
| 元件 | 需求詳細資料 


| NetApp ONTAP | 部分9.7P1及更新版本ONTAP 


| NetApp Active IQ Unified Manager | 需要最新版本的 NetApp Active IQ Unified Manager （目前為 9.13RC1 ） 


| NetApp儲存陣列 | 支援所有的支援功能、包括所有的支援功能、支援所有的支援功能、包括更新版本的支援ONTAP ASA AFF FAS ONTAP 


| 虛擬化Hypervisor | vSphere 6.7及更新版本 
|===

NOTE: 請參閱 https://www.cisco.com/c/en/us/solutions/collateral/data-center-virtualization/flexpod/cisco-imm-for-flexpod.html["Cisco Intersight託管模式FlexPod 、適用於"^] 適用於Cisco UCS運算元件和UCSM版本的最低需求。



== Cisco Intersight授權要求

Cisco Intersight以訂購方式授權、並提供多種授權版本供您選擇。不同授權類型的功能也隨之增加。您可以購買一年、三年或五年的訂閱期間、並選擇所選訂閱期間所需的Cisco UCS Server Volume層。當您存取Cisco Intersight入口網站並索取裝置時、每個Cisco端點都會自動包含Cisco Intersight Base、而且不需額外付費。

您可以使用Cisco訂購工具購買下列任何較高層的Intersight授權：

* * Cisco Intersight Essentials。* Essentials包含基礎層的所有功能、以及其他功能、包括Cisco UCS Central和Cisco IMC主管權限、含服務設定檔的原則型組態、韌體管理、以及與硬體相容性清單（HCL）的相容性評估。
* * Cisco Intersight Advantage * Advantage提供基礎層級和基礎層級的所有功能。其中包括儲存小工具、儲存設備庫存、儲存容量和儲存使用率、以及跨網域的實體運算、實體儲存設備和虛擬環境（VMware ESXi）庫存關聯。
* * Cisco Intersight Premier *除了優勢層提供的功能之外、Cisco Intersight Premier還提供跨Cisco UCS及協力廠商系統（包括虛擬機器（VM）（VMware vCenter）和實體儲存設備（NetApp儲存設備）的私有雲端基礎架構即服務（IaaS）協調功能。


如需各種授權層級所涵蓋功能的詳細資訊、請參閱 https://intersight.com/help/getting_started#intersight_licensing["Cisco授權"]。
